meta_product_name: "Holo Booth 👓"
meta_title: "Holo Booth 👓 - Your instant AR hologram"
meta_description: "Ever wished to create the bad ass holograms of your favorite SF movies? It is time to make it real!"
meta_image: "hope.gif" # should exist in `app/assets/images/`
twitter_account: "@yannlucklein"   # required for Twitter Cards
